// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE


function clearSelection(param) {
  return (window.getSelection && window.getSelection().removeAllRanges());
}

function clamp(min, max, value) {
  var exit = 0;
  if (max !== undefined) {
    var max$1 = max;
    if (value > max$1) {
      return max$1;
    } else {
      exit = 1;
    }
  } else {
    exit = 1;
  }
  if (exit === 1) {
    if (min !== undefined) {
      var min$1 = min;
      if (value < min$1) {
        return min$1;
      } else {
        return value;
      }
    } else {
      return value;
    }
  }
  
}

export {
  clearSelection ,
  clamp ,
  
}
/* No side effect */
